### ISSUE TITLE
The width and height of  E_np and E_np1 in UnDIP_Samson.py are not matched

### ISSUE THREAD

**Issue by renxiaosa00** [BehnoodRasti/UnDIP#3]
II,III = Endmember_extract(img_resh_np_clip,rmax)   
asq=Endmember_reorder2(E_np,E_np1),
E_np,E_np1 has different width and height

**Comment by BehnoodRasti** [comment]
I am not sure what you mean by the width and height. Endmember_reorder2 function is only used to reorder the endmembers to have the same order as the ground truth endmembers. This function might not work for all datasets. Alternatively, you can remove this function. However, you need to match the estimated abundances with the ground truth in the end.
