### ISSUE TITLE
Question about the UnDIP_Samson.p

### ISSUE THREAD

**Issue by OliMiu** [BehnoodRasti/UnDIP#5]
Hi, 

There is a problem with running UnDIP_Samson. I input the Jasper Ridge data into the demo instead of the Samson and kept the settings (5 runs and iter=3000). But there are always two endmembers having the same values in the endmember matrix. What settings should I use to get the correct result?

Best

**Comment by BehnoodRasti** [comment]
Hi, Make sure you change the number of endmembers. It is possible that SiVM selects similar endmembers. This could happen when there is no pure pixel for a particular endmember. UnDIP is not designed for that scenario. In the case of the absence of pure pixels, you can use MiSiCNet (on my GitHub). It is more reliable. Note that, UnDIP is a supervised technique, and MiSiCNet is a blind one.
